project:
  type: website

website:
  title: "Ciência de dados para todos"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/bunoooo
format:
  html:
    theme:
      - pulse
      - custom.scss
editor: visual

